#ifndef MOD_UNSQUEEZE_CAST_TILING_KEY_H
#define MOD_UNSQUEEZE_CAST_TILING_KEY_H

ASCENDC_TPL_ARGS_DECL(ModUnsqueezeCast, ASCENDC_TPL_UINT_DECL(schMode, 1, ASCENDC_TPL_UI_LIST, 0));
ASCENDC_TPL_SEL(ASCENDC_TPL_ARGS_SEL(ASCENDC_TPL_UINT_SEL(schMode, ASCENDC_TPL_UI_LIST, 0)));

#endif